version: "3"
services:
  mysql:
    container_name: mysql-db
    build: ./docker-config/mysql
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=testw3
    expose:
      - 3306
    restart: always
    networks:
      iw3_2020:
        ipv4_address: 172.19.0.2
  iw3:
    #    image: matiasslpknt1/iw3:0.0.6.RELEASE
    build: ./docker-config/spring
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testw3?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - mysql
    restart: always
    networks:
      iw3_2020:
        ipv4_address: 172.19.0.3
networks:
  iw3_2020:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
